name: 'Simulation'

on:
  push:
  pull_request:

jobs:


  lin:
    runs-on: ubuntu-latest
    name: '🐧 Ubuntu 20.04'
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: '⚙️ Install dependencies'
      run: |
        sudo apt update -qq
        sudo apt install -y libssl-dev

    - name: '🔧 Setup GHDL'
      uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm

    - name: '▶️ Test'
      run: ./.github/test.sh sim
      env:
        MAKE: make


  win:
    runs-on: windows-latest
    name: '🟪 MSYS2 MINGW64'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '⚙️ git config autocrlf'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: '🟪 Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-make
          mingw-w64-x86_64-ghdl-llvm
          mingw-w64-x86_64-openssl

    - name: '▶️ Test'
      run: ./.github/test.sh sim
      env:
        MAKE: mingw32-make
